/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 --transform bicho10.glb 
Files: bicho10.glb [2.38MB] > /Users/gonzalo/Desktop/template-ecommerce-react-three-fiber-main/public/models/bicho10-transformed.glb [744.36KB] (69%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bicho10(props) {
  const { nodes, materials } = useGLTF('/models/bicho10-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  )
}

useGLTF.preload('/models/bicho10-transformed.glb')
