/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 --transform burger.glb 
Files: burger.glb [29.12MB] > /Users/gonzalo/Desktop/MenusCoevoProjects/Front-FoodApp-master/public/models/burger-transformed.glb [1.13MB] (96%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Burger(props) {
  const { nodes, materials } = useGLTF('/models/burger-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material_0} scale={6.5} positionY={-2} />
    </group>
  )
}

useGLTF.preload('/models/burger-transformed.glb')
