/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 --transform cuatroQuesos.glb 
Files: cuatroQuesos.glb [4.46MB] > /Users/gonzalo/Desktop/template-ecommerce-react-three-fiber-main/public/models/cuatroQuesos-transformed.glb [311.18KB] (93%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function CuatroQuesos(props) {
  const { nodes, materials } = useGLTF('/models/cuatroQuesos-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0001.geometry} material={materials['Material_0.001']}  scale={3.5} position={[0,-0.4,0]} />
    </group>
  )
}

useGLTF.preload('/models/cuatroQuesos-transformed.glb')
