/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 --transform serrano.glb 
Files: serrano.glb [3.9MB] > /Users/gonzalo/Desktop/MenusCoevoProjects/Front-FoodApp-master/public/models/serrano-transformed.glb [465.64KB] (88%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Serrano(props) {
  const { nodes, materials } = useGLTF('/models/serrano-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material_0} />
    </group>
  )
}

useGLTF.preload('/models/serrano-transformed.glb')
