/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 --transform PizzaOptimizada2.glb 
Files: PizzaOptimizada2.glb [3.11MB] > /Users/gonzalo/Desktop/template-ecommerce-react-three-fiber-main/public/models/PizzaOptimizada2-transformed.glb [274.01KB] (91%)
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap';

export function ModelPizza1(props) {
  const { nodes, materials } = useGLTF('/models/PizzaOptimizada2-transformed.glb')
  const refModel = useRef();
  useEffect(() => {
    if (props.inView){
      gsap.to(refModel.current.scale, {x: 1, y: 1, z: 1, duration: 3})
    }else{
      gsap.to(refModel.current.scale, {x: 0.1, y: 0.1, z: 0.1, duration: 3})
    }
  }, [props.inView]);
  return (
    <group {...props} dispose={null} scale={[0.1,0.1,0.1]} ref={refModel}>
      <mesh geometry={nodes.pizza.geometry} material={materials.pizza} scale={0.022} />
    </group>
  )
}

useGLTF.preload('/models/PizzaOptimizada2-transformed.glb')
