/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 --transform PizzaOptimizada3.glb 
Files: PizzaOptimizada3.glb [133.2KB] > /Users/gonzalo/Desktop/template-ecommerce-react-three-fiber-main/public/models/PizzaOptimizada3-transformed.glb [10.23KB] (92%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ModelPizza2(props) {
  const { nodes, materials } = useGLTF('/models/PizzaOptimizada3-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.PizzaFungi.geometry} material={materials.Pizza} scale={11.989} />
    </group>
  )
}

useGLTF.preload('/models/PizzaOptimizada3-transformed.glb')
